version: "3"

services:
    next-app:
        container_name: project10k_api
        build:
            context: ./apps/project10k-client/
            dockerfile: Dockerfile
            args:
                ENV_VARIABLE: ${ENV_VARIABLE}
                NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        restart: always
        ports:
            - 3001:3001
        networks:
            - project10k_network

    # Add more containers below (nginx, postgres, etc.)

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    project10k_network:
        external: true
