services:
    next-app:
        container_name: project10k_client
        build:
            context: .
            dockerfile: Dockerfile
            args:
                ENV_VARIABLE: ${ENV_VARIABLE}
                NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}
        restart: always
        ports:
            - 3000:3000
        networks:
            - backend_network
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        restart: always
        ports:
            - 80:80
        networks:
            - backend_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
    backend_network:
        name: project10k-server_backend
        external: true
